config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/ncut-admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # omniauth_callbacks: "users/omniauth_callbacks",
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"


  resources :flashes

  resources :user_infos

  resources :admin do
    collection do
      get :user_manage
      get :user_response
      get :click_rates
      get :user_activity

      resources :courses
      resources :course_topics
      resources :yellow
    end
  end

  resources :user

  resources :ctrs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_topics

  validates :name, presence: true

  enum status: [:is_hidden, :is_published]
end

app/models/course_topic.rb
class CourseTopic < ApplicationRecord
  belongs_to :course

  validates_numericality_of :course_id, greater_than_or_equal_to: 1
  validates_numericality_of :number, greater_than_or_equal_to: 0
  validates :eng_topic, :chi_topic, presence: true
end

app/models/ctr.rb
class Ctr < ApplicationRecord

  validates :user_id, :scenes, :inserted_at, presence: true
  validates_numericality_of :user_id, greater_than_or_equal_to: 1

end

app/models/quiz_score.rb
class QuizScore < ApplicationRecord

  validates_numericality_of :user_id, greater_than_or_equal_to: 1
  validates_numericality_of :score, greater_than_or_equal_to: 0
  validates_numericality_of :use_time, greater_than: 1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  validates :name, :student_class, :role, presence: true
  enum role: [:guest, :student, :admin]

  mount_uploader :avator, CoverImageUploader

  has_many :user_infos


  protected
  # 這段程式碼的用意是在資料表可以看見current_sign_in_at這些欄位，但是在 rails console裡面看不到
  # 所以加上這段程式碼可以在 rails console 裡面看到這些欄位
  # 但是真正在執行的時候必須要註解掉，不然會報錯
  # def serializable_hash(options = nil)
  #   super(options).merge(current_sign_in_at: current_sign_in_at, last_sign_in_at: last_sign_in_at) # you can keep adding attributes here that you wish to expose
  # end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user

  validates :user_id, :scenes, :topic, :input_data, presence: true

end

app/models/yellow.rb
class Yellow < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin/layouts/admin'

  def index   #Dashboard頁面
    @recent_log_in_users = User.order(current_sign_in_at: :desc)   #搜尋最近登入 User 使用 Desc 排序

    log_in_user = User.where(current_sign_in_at: Date.current.to_time.all_day)  #搜尋 User登入時間是否符合今天日期
    @today_log_in_users = log_in_user.count  #計算今天登入的 User數量

    practice = UserInfo.where(inserted_at: Date.current.to_time.all_day)   #搜尋當天日期的練習量
    @today_practice_count = practice.count   #今日練習量
  end

  def user_manage  #用戶管理頁面
    @users = User.all     #搜尋所有 User
    @edit_user = User.first  #後台按下編輯按鈕尋找 User
  end


  def user_response  #學生作答紀錄
    @user_response = User.find_by_sql("select * from users inner join user_infos on users.id = user_infos.user_id order by inserted_at desc")  #搜尋 User join UserInfo
  end

  def click_rates  #點擊率頁面
    @users = Ctr.find_by_sql("select distinct users.id, users.name from users inner join ctrs on users.id = ctrs.user_id")
    @courses = Course.select(:name, :id).order(:id).distinct
    @array1 = []
    @array2 = []
    @i = 0

    @users.each_with_index do |users|
      @array1.push(users.name)
      @courses.each_with_index do |courses|
        click_rates_count = Ctr.where(:user_id => users.id).where(:scenes => courses.name).count
        @array1.push(click_rates_count)
      end
      @array2.push(@array1)
      @array1 = []
    end
  end

  def user_activity
    @users = User.where(:role => 1)  #只記錄學生登入情況
  end

end

app/controllers/ctrs_controller.rb
class CtrsController < ApplicationController

  def create
    click_rates = Ctr.create({
                               user_id: current_user.id,
                               scenes: params[:ctr][:scenes],
                               inserted_at: Time.zone.now
                             })
  end

end

app/controllers/flashes_controller.rb
class FlashesController < ApplicationController
  before_action :redirect_if_not_log_in
  before_action :redirect_if_role_is_guest

  LIMITED_QUESTION_NUMBER = 1  #每頁顯示一個問題

  def index
    @courses = Course.all.order("id")
  end

  def show
    @course = Course.find_by_id(params[:id])
    @course_topics = CourseTopic.where(:course_id => @course).order("id")

    @count = @course_topics.count  #總共有幾個問題

    # 如果網址沒有page的話，他會顯示最後一個問題，這樣是錯的，應該是顯示第一個問題，所以要加判斷
    if params[:page]
      @page = params[:page].to_i    # 從 params 拿進來的值是字串，所以要轉成 integer
    else
      @page = 1
    end

    #將 course_topics分成一頁一題
    @first_page = 1
    @last_page = ( @count / LIMITED_QUESTION_NUMBER )
    @course_topics = @course_topics[ (@page - 1) * LIMITED_QUESTION_NUMBER, LIMITED_QUESTION_NUMBER]


    @user_info = UserInfo.new  #建立一個空的 UserInfo

    @click_rates = Ctr.new  #建立一個空的 CTR
  end



  private

  def redirect_if_not_log_in
    if !current_user
      flash[:notice] = "您尚未登入"
      redirect_to root_path
      return
    end
  end

  def redirect_if_role_is_guest
    if current_user && current_user.role == 'guest'
      flash[:notice] = "你的帳號尚未開通，請稍等老師為您開通"
      redirect_to root_path
      return
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.count         #註冊的會員數量
    @courses = Course.count     #課程數量


    practice = UserInfo.where(inserted_at: Date.current.to_time.all_day)   #搜尋當天日期的練習量
    @today_practice_count = practice.count   #今日練習量

    log_in_user = User.where(current_sign_in_at: Date.current.to_time.all_day)  #搜尋 User登入時間是否符合今天日期
    @today_log_in_user = log_in_user.count  #計算今天登入的 User數量
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def update
    user = User.find_by(id: params[:id])

    if user.update(user_edit_permit)
      redirect_to user_manage_admin_index_path
    end
  end


  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:notice] = "成功刪除!!"
    redirect_to user_manage_admin_index_path
    return
  end


  private

  def user_edit_permit
    params.require(:user).permit([:name, :student_class, :email, :role]) #[裡面的欄位名稱是資料表裡面的欄位名稱，不是表單的名稱]
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/ctrs_helper.rb
module CtrsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/yellow_helper.rb
module YellowHelper
end

app/views/flashes/index.html.erb
<div class="mb-4">
  <ul id="myTab" role="tablist" class="nav justify-content-center nav-tabs nav-pills text-center border-0 rounded-nav">
    <% @courses.each_with_index do |c, index| %>
      <%= link_to flash_path(c) do %>
        <button type="button" class="btn btn-outline-primary btn-lg" style="margin: 5px"><%= c.name %></button>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/flashes/show.html.erb
<div class="container">
    <div id="myTabContent" class="tab-content" style="text-align:center">
      <% @course_topics.each_with_index do |ct| %>
        <% if !params[:page] %>
          <h3 id="topic1" class="mb-3"><%= "1" + "." + ct.chi_topic %></h3>
        <% else %>
          <h3 id="topic1" class="mb-3"><%= params[:page] + "." + ct.chi_topic %></h3>
        <% end %>
      <% end %>

      <%= form_for @user_info, method: :post do |f| %>
        <div class="">
            <%= f.hidden_field :scenes, value: @course.name %>
            <%= f.hidden_field :scenes_id, value: @course.id %>
            <%= f.hidden_field :count, value: @count %>
            <% if !params[:page] %>
              <%= f.hidden_field :topic, value: 1  %>
            <% else %>
              <%= f.hidden_field :topic, value: params[:page] %>
            <% end %>
          <div class="textarea">
            <%= f.text_area :input_data, class: "form-control", placeholder: "在此輸入英文句子", rows: 5, cols: 10, id: "text_area"  %>
          </div>
          <%= f.submit "繳交題目", class: "btn btn-outline-dark btn-lg mt-2", id: "submit1" %>
        </div>
      <% end %>

      <%= form_for @click_rates, html: {id: "click_rates_form"} do |f| %>
        <%= f.hidden_field :scenes, value: @course.name %>
      <% end %>

      <h3 id="topic_write" class="mb-3" >默寫模式</h3>

      <% @course_topics.each_with_index do |ct| %>
        <% if !params[:page] %>
          <h3 id="topic_eng" class="mb-3" style="display: none"><%= "1" + "." + ct.eng_topic %></h3>
        <% else %>
          <h3 id="topic_eng" class="mb-3" style="display: none"><%= params[:page] + "." + ct.eng_topic %></h3>
        <% end %>
      <% end %>

      <audio id="audio" >Your browser does not support the audio element.</audio>

      <%= link_to "回到題目頁面", flashes_path, class: "btn btn-outline-info btn-lg" %>

      <% if @page > @first_page %>
          <%= link_to flash_path(page: (@page - 1)) do %>
        <button type="button" class="btn btn-outline-dark btn-lg" onclick="prevpage()">上題</button>
          <% end %>
      <% else %>
          <%= link_to flash_path(page: (@page - 1)) do %>
            <button type="button" disabled="disabled" class="btn btn-outline-dark btn-lg" onclick="prevpage()">上題</button>
          <% end %>
      <% end %>

      <% if @page < @last_page %>
          <%= link_to flash_path(page: (@page + 1)) do %>
            <button type="button" class="btn btn-outline-dark btn-lg" onclick="nextpage()">下題</button>
          <% end %>
      <% else %>
          <%= link_to flash_path(page: (@page + 1)) do %>
            <button type="button" disabled="disabled" class="btn btn-outline-dark btn-lg" onclick="nextpage()">下題</button>
          <% end %>
      <% end %>


      <button type="button" class="btn btn-outline-primary btn-lg" onclick="playAudio()">複誦</button>
      <button type="button" class="btn btn-outline-secondary btn-lg" onclick="dictation()">默寫</button>
      <button type="button" class="btn btn-outline-success btn-lg" onclick="check()">核對</button>
      <button type="button" class="btn btn-outline-danger btn-lg" onclick="random()">抽題</button>

    </div>
</div>


<script type="text/javascript">
    var x = document.getElementById("audio");
    var course_id = <%= @course.id %>


    <% if params[:page] %>
      var topic_id = <%= params[:page] %>
    <% else %>
      var topic_id = 1
    <% end %>

    random_topic = Math.floor(Math.random()*<%= @count %>)+1

    function dictation(){
        $("#topic_write").show();
        $("#topic_eng").hide()
    }

    function check(){
        $("#topic_eng").show();
        $("#topic_write").hide()
    }

    function playAudio() {
        $("audio").attr('src',"/data/" + course_id + "/LS/PAUL/" + topic_id + ".mp3");
        x = document.getElementById("audio");
        x.play();
    }


    function random() {
        window.location.replace("http://127.0.0.1:3000/flashes/"+course_id+"?page="+random_topic)
    }


    $(document).ready(function (){
        let textarea = $("#text_area")
        $("#submit1").click( function (){
           if (textarea.val().length > 0 ) {
               alert("繳交成功!!")
           }
           else {
               alert("請輸入答案!!")
           }
        })
    })


    // 點擊率表單自動送出
    $(function (){
        let current_url = window.location.href
        if (current_url == "http://127.0.0.1:3000/flashes/"+course_id) {
            $("#click_rates_form").submit()
        }
    })


</script>