config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/ncut-admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # omniauth_callbacks: "users/omniauth_callbacks",
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"


  resources :flashes

  resources :user_infos

  resources :admin do
    collection do
      get :user_manage
      get :user_response
      get :click_rates
      get :user_activity

      resources :courses
      resources :course_topics
      resources :yellow
    end
  end

  resources :user

  resources :ctrs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_topics

  validates :name, presence: true

  enum status: [:is_hidden, :is_published]
end

app/models/course_topic.rb
class CourseTopic < ApplicationRecord
  belongs_to :course

  validates_numericality_of :course_id, greater_than_or_equal_to: 1
  validates_numericality_of :number, greater_than_or_equal_to: 0
  validates :eng_topic, :chi_topic, presence: true
end

app/models/ctr.rb
class Ctr < ApplicationRecord

  validates :user_id, :scenes, :inserted_at, presence: true
  validates_numericality_of :user_id, greater_than_or_equal_to: 1

end

app/models/quiz_score.rb
class QuizScore < ApplicationRecord

  validates_numericality_of :user_id, greater_than_or_equal_to: 1
  validates_numericality_of :score, greater_than_or_equal_to: 0
  validates_numericality_of :use_time, greater_than: 1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  validates :name, :student_class, :role, presence: true
  enum role: [:guest, :student, :admin]

  mount_uploader :avator, CoverImageUploader

  has_many :user_infos


  protected
  # 這段程式碼的用意是在資料表可以看見current_sign_in_at這些欄位，但是在 rails console裡面看不到
  # 所以加上這段程式碼可以在 rails console 裡面看到這些欄位
  # 但是真正在執行的時候必須要註解掉，不然會報錯
  # def serializable_hash(options = nil)
  #   super(options).merge(current_sign_in_at: current_sign_in_at, last_sign_in_at: last_sign_in_at) # you can keep adding attributes here that you wish to expose
  # end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user

  validates :user_id, :scenes, :topic, :input_data, presence: true

end

app/models/yellow.rb
class Yellow < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin/layouts/admin'

  def index   #Dashboard頁面
    @recent_log_in_users = User.order(current_sign_in_at: :desc)   #搜尋最近登入 User 使用 Desc 排序

    log_in_user = User.where(current_sign_in_at: Date.current.to_time.all_day)  #搜尋 User登入時間是否符合今天日期
    @today_log_in_users = log_in_user.count  #計算今天登入的 User數量

    practice = UserInfo.where(inserted_at: Date.current.to_time.all_day)   #搜尋當天日期的練習量
    @today_practice_count = practice.count   #今日練習量
  end

  def user_manage  #用戶管理頁面
    @users = User.all     #搜尋所有 User
    @edit_user = User.first  #後台按下編輯按鈕尋找 User
  end


  def user_response  #學生作答紀錄
    @user_response = User.find_by_sql("select * from users inner join user_infos on users.id = user_infos.user_id order by inserted_at desc")  #搜尋 User join UserInfo
  end

  def click_rates  #點擊率頁面
    @users = Ctr.find_by_sql("select distinct users.id, users.name from users inner join ctrs on users.id = ctrs.user_id")
    @courses = Course.select(:name, :id).order(:id).distinct
    @array1 = []
    @array2 = []
    @i = 0

    @users.each_with_index do |users|
      @array1.push(users.name)
      @courses.each_with_index do |courses|
        click_rates_count = Ctr.where(:user_id => users.id).where(:scenes => courses.name).count
        @array1.push(click_rates_count)
      end
      @array2.push(@array1)
      @array1 = []
    end
  end

  def user_activity
    @users = User.where(:role => 1)  #只記錄學生登入情況
  end

end

app/controllers/ctrs_controller.rb
class CtrsController < ApplicationController

  def create
    click_rates = Ctr.create({
                               user_id: current_user.id,
                               scenes: params[:ctr][:scenes],
                               inserted_at: Time.zone.now
                             })
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.count         #註冊的會員數量
    @courses = Course.count     #課程數量


    practice = UserInfo.where(inserted_at: Date.current.to_time.all_day)   #搜尋當天日期的練習量
    @today_practice_count = practice.count   #今日練習量

    log_in_user = User.where(current_sign_in_at: Date.current.to_time.all_day)  #搜尋 User登入時間是否符合今天日期
    @today_log_in_user = log_in_user.count  #計算今天登入的 User數量
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def update
    user = User.find_by(id: params[:id])

    if user.update(user_edit_permit)
      redirect_to user_manage_admin_index_path
    end
  end


  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:notice] = "成功刪除!!"
    redirect_to user_manage_admin_index_path
    return
  end


  private

  def user_edit_permit
    params.require(:user).permit([:name, :student_class, :email, :role]) #[裡面的欄位名稱是資料表裡面的欄位名稱，不是表單的名稱]
  end

end

app/controllers/yellow_controller.rb
class YellowController < ApplicationController
    layout 'admin/layouts/admin'

    def index
        @yellows = Yellow.all
    end

    def edit
        @yellow = Yellow.find_by_id(params[:id])
    end

    def create  #新增Yellow詞彙

        count = 0

        unless params[:Verb].blank?
            count += 1
        end

        unless params[:Noun].blank?
            count += 1
        end

        unless params[:Adjective].blank?
            count += 1
        end

        unless params[:Adverb].blank?
            count += 1
        end

        yellow = Yellow.create(yellow_permit.merge({Count: count}))

        if yellow.valid?
            redirect_to action: :index
            return
        end
    end

    def update
        yellow = Yellow.find(params[:id])

        compare_count = 0  #用來比對count是否有增減

        count = params[:Count].to_i  #原本的Count數量

        unless params[:Verb].blank?
            compare_count += 1
        end

        unless params[:Noun].blank?
            compare_count += 1
        end

        unless params[:Adjective].blank?
            compare_count += 1
        end

        unless params[:Adverb].blank?
            compare_count += 1
        end

        if count > compare_count
            compare_total = count - compare_count  #比對出來差多少 ex. 差1或差2
            count -=  compare_total   #Count要減去差的數量
        elsif count < compare_count
            compare_total = compare_count - count  #比對出來差多少 ex. 多1或多2
            count += compare_total  #Count要加上差的數量
        end


        if yellow.update(yellow_permit.merge({Count: count}))
            redirect_to action: :index
            return
        end
    end

    private

    def yellow_permit
        params.permit([:Verb, :Noun, :Adjective, :Adverb])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_topics_helper.rb
module CourseTopicsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/ctrs_helper.rb
module CtrsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/yellow_helper.rb
module YellowHelper
end

app/views/yellow/edit.html.erb
<% content_for :title, "Yellow-Edit" %>

<% content_for :script do %>
    <script src="/global_assets/js/demo_pages/datatables_extension_buttons_print.js"></script>
    <script src="/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
    <script src="/global_assets/js/plugins/tables/datatables/extensions/select.min.js"></script>
<% end %>

<div class="row">
    <div class="card col-lg">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">修改詞彙(黃色區塊)</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="mb-4"></p>
            <%= form_tag("/admin/yellow/#{@yellow.id}", method: :put) do %>
                <fieldset class="mb-3">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Verb:</label>
                                <input type="text" name="Verb" class="form-control" placeholder="add" value="<%= @yellow.Verb %>">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Noun:</label>
                                <input type="text" name="Noun" class="form-control" placeholder="addition" value="<%= @yellow.Noun %>">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Adjective:</label>
                                <input type="text" name="Adjective" class="form-control" placeholder="additional" value="<%= @yellow.Adjective %>">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Adverb:</label>
                                <input type="text" name="Adverb" class="form-control" placeholder="additionally" value="<%= @yellow.Adverb %>">
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="Count" class="form-control" placeholder="" value="<%= @yellow.Count %>">
                </fieldset>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">
                        修改
                        <i class="icon-paperplane ml-2"></i>
                    </button>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/yellow/index.html.erb
<% content_for :title, "Yellow" %>

<% content_for :script do %>
    <script src="/global_assets/js/demo_pages/datatables_extension_buttons_print.js"></script>
    <script src="/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
    <script src="/global_assets/js/plugins/tables/datatables/extensions/select.min.js"></script>
<% end %>

<!-- 顯示所有Yellow詞彙 -->
<div class="row">
    <div class="card col-lg">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Yellow</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <table class="table datatable-button-print-rows" style="font-size:16px">
            <thead>
            <tr>
                <td>No.</td>
                <td>Verb</td>
                <td>Noun</td>
                <td>Adjective</td>
                <td>Adverb</td>
                <td>編輯</td>
            </tr>
            </thead>
            <tbody>
            <% @yellows.each do |yellow| %>
            <tr>
                <td><%= yellow.id %></td>
                <td><%= yellow.Verb %></td>
                <td><%= yellow.Noun %></td>
                <td><%= yellow.Adjective %></td>
                <td><%= yellow.Adverb %></td>
                <td>
                    <%= link_to edit_yellow_path(yellow) do %>
<!--                    <form action="{{route('yellow.edit' , $data->id)}}" method="get" style="margin-top: 0px;margin-bottom: 0px;">-->
                        <button title="編輯單字" class="btn btn-xs btn-icon btn-inverse btn-round" data-toggle="tooltip" data-original-title="remove">
                            <i class="icon-pencil3" ></i>
                        </button>
<!--                    </form>-->
                    <% end %>
                </td>
            </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>


<!-- 新增Yellow詞彙 -->

<div class="row">
    <div class="card col-lg">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">新增詞彙(黃色區塊)</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="mb-4"></p>
            <%= form_tag("/admin/yellow", method: :post) do %>
                <fieldset class="mb-3">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Verb:</label>
                                <input type="text" name="Verb" class="form-control" placeholder="add">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Noun:</label>
                                <input type="text" name="Noun" class="form-control" placeholder="addition">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Adjective:</label>
                                <input type="text" name="Adjective" class="form-control" placeholder="additional">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Adverb:</label>
                                <input type="text" name="Adverb" class="form-control" placeholder="additionally">
                            </div>
                        </div>
                    </div>

                    <input type="hidden" id="audio_url" name="audiourl" value="">
                </fieldset>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">
                        新增
                        <i class="icon-paperplane ml-2"></i>
                    </button>
                </div>
            <% end %>
        </div>
    </div>
</div>