config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/ncut-admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    # omniauth_callbacks: "users/omniauth_callbacks",
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"


  resources :flashes

  resources :user_infos

  resources :admin do
    collection do
      get :user_manage
      get :user_response
      get :click_rates
      get :user_activity

      resources :courses
      resources :course_topics
      resources :yellow
    end
  end

  resources :user

  resources :ctrs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_topics

  validates :name, presence: true

  enum status: [:is_hidden, :is_published]
end

app/models/course_topic.rb
class CourseTopic < ApplicationRecord
  belongs_to :course

  validates_numericality_of :course_id, greater_than_or_equal_to: 1
  validates_numericality_of :number, greater_than_or_equal_to: 0
  validates :eng_topic, :chi_topic, presence: true
end

app/models/ctr.rb
class Ctr < ApplicationRecord

  validates :user_id, :scenes, :inserted_at, presence: true
  validates_numericality_of :user_id, greater_than_or_equal_to: 1

end

app/models/quiz_score.rb
class QuizScore < ApplicationRecord

  validates_numericality_of :user_id, greater_than_or_equal_to: 1
  validates_numericality_of :score, greater_than_or_equal_to: 0
  validates_numericality_of :use_time, greater_than: 1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  validates :name, :student_class, :role, presence: true
  enum role: [:guest, :student, :admin]

  mount_uploader :avator, CoverImageUploader

  has_many :user_infos


  protected
  # 這段程式碼的用意是在資料表可以看見current_sign_in_at這些欄位，但是在 rails console裡面看不到
  # 所以加上這段程式碼可以在 rails console 裡面看到這些欄位
  # 但是真正在執行的時候必須要註解掉，不然會報錯
  # def serializable_hash(options = nil)
  #   super(options).merge(current_sign_in_at: current_sign_in_at, last_sign_in_at: last_sign_in_at) # you can keep adding attributes here that you wish to expose
  # end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user

  validates :user_id, :scenes, :topic, :input_data, presence: true

end

app/models/yellow.rb
class Yellow < ApplicationRecord
end

app/controllers/ctrs_controller.rb
class CtrsController < ApplicationController

  def create
    click_rates = Ctr.create({
                               user_id: current_user.id,
                               scenes: params[:ctr][:scenes],
                               inserted_at: Time.zone.now
                             })
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.count         #註冊的會員數量
    @courses = Course.count     #課程數量


    practice = UserInfo.where(inserted_at: Date.current.to_time.all_day)   #搜尋當天日期的練習量
    @today_practice_count = practice.count   #今日練習量

    log_in_user = User.where(current_sign_in_at: Date.current.to_time.all_day)  #搜尋 User登入時間是否符合今天日期
    @today_log_in_user = log_in_user.count  #計算今天登入的 User數量
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def update
    user = User.find_by(id: params[:id])

    if user.update(user_edit_permit)
      redirect_to user_manage_admin_index_path
    end
  end


  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:notice] = "成功刪除!!"
    redirect_to user_manage_admin_index_path
    return
  end


  private

  def user_edit_permit
    params.require(:user).permit([:name, :student_class, :email, :role]) #[裡面的欄位名稱是資料表裡面的欄位名稱，不是表單的名稱]
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/ctrs_helper.rb
module CtrsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/yellow_helper.rb
module YellowHelper
end

app/views/admin/click_rates.html.erb
<% content_for :title, "學生點擊狀況紀錄" %>

<% content_for :script do %>
  <script src="/global_assets/js/demo_pages/datatables_extension_buttons_print.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/extensions/select.min.js"></script>
<% end %>

<div class="row">
  <div class="card col-lg">
    <div class="card-header header-elements-inline">
      <h5 class="card-title">學生點擊狀況紀錄</h5>
      <div class="header-elements">
        <div class="list-icons">
          <a class="list-icons-item" data-action="collapse"></a>
          <a class="list-icons-item" data-action="reload"></a>
          <a class="list-icons-item" data-action="remove"></a>
        </div>
      </div>
    </div>

    <table class="table datatable-button-print-rows" style="font-size:16px">
      <thead>
        <tr>
          <td>Name</td>
          <% @courses.each_with_index do |courses| %>
          <td><%= courses.name %></td>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @array2.each  do |ary2| %>
        <tr>
          <% while @i < ary2.count %>
            <td><%= ary2[@i] %></td>
            <% @i += 1 %>
          <% end %>
          <% @i = 0 %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<!--當 @i 小於 ary2.count 跑迴圈執行 <td>-->
<!--@i += 1-->
<!--當迴圈執行完畢-->
<!--重置 @i = 0-->

app/views/admin/index.html.erb
<% content_for :title, "Dashboard" %>

<div class="row">
  <div class="col-xl-7">
    <div class="card">
      <div class="card-header header-elements-inline">
        <h5 class="card-title">最近登入的使用者</h5>
        <div class="header-elements">
          <div class="list-icons">
            <a class="list-icons-item" data-action="collapse"></a>
            <a class="list-icons-item" data-action="reload"></a>
            <a class="list-icons-item" data-action="remove"></a>
          </div>
        </div>
      </div>
      <table class="table datatable-button-print-rows" style="font-size:16px">
        <thead>
        <tr>
          <th>最近登入時間</th>
          <th>姓名</th>
          <th>班級</th>
        </tr>
        </thead>
        <tbody>
        <% @recent_log_in_users.each_with_index do  |s| %>
        <tr>
          <td><span class="badge badge-success"><%= s.current_sign_in_at %></span></td>
          <td><%= s.name %></td>
          <td><%= s.student_class %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-xl-5">
    <div class="row">
      <div class="col-lg-6">
        <!-- Members online -->
        <div class="card bg-teal-400">
          <div class="card-body">
            <div class="d-flex">
              <h3 class="font-weight-semibold mb-0"><%= @today_log_in_users %></h3>
              <span class="badge bg-teal-800 badge-pill align-self-center ml-auto">+53,6%</span>
            </div>

            <div>
              今日拜訪人數
              <div class="font-size-sm opacity-75">489 avg</div>
            </div>
          </div>

          <div class="container-fluid">
            <div id="members-online"></div>
          </div>
        </div>
        <!-- /members online -->
      </div>
      <div class="col-lg-6">
        <!-- Today's revenue -->
        <div class="card bg-blue-400">
          <div class="card-body">
            <div class="d-flex">
              <h3 class="font-weight-semibold mb-0"><%= @today_practice_count %></h3>
              <div class="list-icons ml-auto">
                <a class="list-icons-item" data-action="reload"></a>
              </div>
            </div>
            <div>
              今日練習量
              <div class="font-size-sm opacity-75">37,578 avg</div>
            </div>
          </div>
          <div id="today-revenue"></div>
        </div>
        <!-- /today's revenue -->
      </div>
    </div>
  </div>
  <!-- /form inputs -->
</div>

app/views/admin/layouts/_footer.html.erb
<div class="navbar navbar-expand-lg">
  <div class="text-center d-lg-none w-100">
    <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
      <i class="icon-unfold mr-2"></i>
      Footer
    </button>
  </div>
  <div class="navbar-collapse collapse" id="navbar-footer">
    <span class="navbar-text">
        &copy; 2020. <a href="#">會展英文 web site</a> by <a href="http://muxlink.com.tw" target="_blank">NCUT IM CHUN LIN</a>
    </span>
  </div>
</div>

app/views/admin/layouts/_nav.html.erb
<div class="navbar navbar-expand-md navbar-dark header-shadow">
  <div class="navbar-brand">
    <!-- <div style="margin-right:15px"> -->
    <%= link_to admin_index_path, class: "d-inline-block" do %>
      <img src="/global_assets/images/logo_light.png" alt="">
    <% end %>
  </div>

  <!-- </div> -->

  <div class="d-md-none">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
      <i class="icon-tree5"></i>
    </button>
    <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
      <i class="icon-paragraph-justify3"></i>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="navbar-mobile">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
          <i class="icon-paragraph-justify3"></i>
        </a>
      </li>
    </ul>

    <span class="badge bg-success ml-md-3 mr-md-auto">Online</span>

    <ul class="navbar-nav">
      <li class="nav-item dropdown dropdown-user">
        <a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
          <img src="/global_assets/images/demo/users/face11.jpg" class="rounded-circle mr-2" height="34" alt="">
          <span>管理員</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to '登出', destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/admin/layouts/_sidebar.html.erb
<!-- Main sidebar -->
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

  <!-- Sidebar mobile toggler -->
  <div class="sidebar-mobile-toggler text-center">
    <a href="#" class="sidebar-mobile-main-toggle">
      <i class="icon-arrow-left8"></i>
    </a>
    Navigation
    <a href="#" class="sidebar-mobile-expand">
      <i class="icon-screen-full"></i>
      <i class="icon-screen-normal"></i>
    </a>
  </div>
  <!-- /sidebar mobile toggler -->

  <!-- Sidebar content -->
  <div class="sidebar-content">
    <!-- User menu -->
    <div class="sidebar-user">
      <div class="card-body">
        <div class="media">
          <div class="mr-3">
            <a href="#"><img src="/global_assets/images/demo/users/face11.jpg" width="38" height="38" class="rounded-circle" alt=""></a>
          </div>
          <div class="media-body">
            <div class="media-title font-weight-semibold">Admin</div>
            <div class="font-size-xs opacity-50">
              <i class="icon-pin font-size-sm"></i> &nbsp歡迎 管理員
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /user menu -->

    <!-- Main navigation -->
    <div class="card card-sidebar-mobile">
      <ul class="nav nav-sidebar" data-nav-type="accordion">
        <!-- Main -->
        <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
        <li class="nav-item">
          <%= link_to admin_index_path, class: "nav-link active" do %>
            <i class="icon-home4"></i>
            <span>
              Dashboard
            </span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_manage_admin_index_path, class: "nav-link " do %>
            <i class="icon-user"></i>
            <span>
              用戶管理
            </span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_response_admin_index_path, class: "nav-link " do %>
            <i class="icon-pencil6"></i>
            <span>
              學生作答紀錄
            </span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to click_rates_admin_index_path, class: "nav-link " do %>
            <i class="icon-mouse-left"></i>
            <span>
              點擊率
            </span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_activity_admin_index_path, class: "nav-link " do %>
            <i class="icon-file-text"></i>
            <span>
              活動紀錄
            </span>
          <% end %>
        </li>
        <li class="nav-item nav-item-submenu">
          <a href="#" class="nav-link"><i class="icon-pencil5"></i>
            <span>
              我的課程
            </span>
          </a>
          <ul class="nav nav-group-sub" data-submenu-title="Layouts">
            <li class="nav-item">
              <%= link_to "情境編輯", courses_path, class: "nav-link " %>
            </li>
            <li class="nav-item">
              <%= link_to "課程編輯", course_topics_path, class: "nav-link " %>
            </li>
          </ul>
        </li>
        <li class="nav-item nav-item-submenu">
          <a href="#" class="nav-link">
            <i class="icon-pencil5"></i>
            <span>
              考試
            </span>
          </a>
          <ul class="nav nav-group-sub" data-submenu-title="quiz">
            <li class="nav-item">
                <%= link_to "黃色區塊", yellow_index_path, class: "nav-link " %>
            </li>
            <li class="nav-item">
              <a href="" class="nav-link">學生考試狀況</a>
            </li>
          </ul>
        </li>
        <!-- /main -->
      </ul>
    </div>
    <!-- /main navigation -->
  </div>
  <!-- /sidebar content -->
</div>
<!-- /main sidebar -->

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>
    會展英文
  </title>
  <meta name="description" content="國立勤益科技大學應英系老師個人教學網站" />
  <meta name="keywords" content="Bootstrap, 網站, 開發, 程式, 設計, 教學, jquery, HTML, HTML5, CSS, JavaScript, Swift, WordPress, iOS, Ruby On Rails, Arduino">
  <meta name="copyright" content="國立勤益科技大學">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
  <link href="/global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/bootstrap_limitless.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/layout.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/components.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/colors.min.css" rel="stylesheet" type="text/css">

  <%= javascript_include_tag 'application' %>
  <script src="/global_assets/js/main/jquery.min.js"></script>
  <script src="/global_assets/js/main/bootstrap.bundle.min.js"></script>
  <script src="/global_assets/js/plugins/loaders/blockui.min.js"></script>

  <script src="/global_assets/js/plugins/forms/validation/validate.min.js"></script>
  <script src="/global_assets/js/plugins/forms/inputs/touchspin.min.js"></script>
  <script src="/global_assets/js/plugins/forms/selects/select2.min.js"></script>
  <script src="/global_assets/js/plugins/forms/styling/switch.min.js"></script>
  <script src="/global_assets/js/plugins/forms/styling/switchery.min.js"></script>
  <script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>
  <script src="/assets/js/app.js"></script>
  <%= yield :script %>

  </head>

<body>

<%= render partial: 'admin/layouts/nav' %>
<%= render partial: 'layouts/notice' %>
<!-- Page content -->
<div class="page-content">

  <%= render partial: 'admin/layouts/sidebar' %>

  <!-- Main content -->
  <div class="content-wrapper">
    <!-- Page header -->
    <!-- <div class="page-header page-header-light"> -->
    <div class="page-header">
      <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
          <div class="breadcrumb">
            <%= link_to admin_index_path, class: "breadcrumb-item" do %>
              <i class="icon-home2 mr-2"></i>
              Home
            <% end %>
            <a href="javascript:void(0);" class="breadcrumb-item"><%= yield(:title) %></a>
          </div>
          <a href="#" class="header-elements-toggle text-default d-md-none">
            <i class="icon-more"></i>
          </a>
        </div>
        <div class="header-elements d-none">
          <div class="breadcrumb justify-content-center">
            <div class="breadcrumb-elements-item dropdown p-0">
              <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                <i class="icon-gear mr-2"></i>
                Settings
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class="dropdown-item">
                  <i class="icon-gear"></i>
                  All settings
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
          <h4>
            <i class="icon-arrow-left52 mr-2"></i>
            <span class="font-weight-semibold">
              Home
            </span> - Dashboard
          </h4>
          <a href="#" class="header-elements-toggle text-default d-md-none">
            <i class="icon-more"></i>
          </a>
        </div>
      </div>
    </div>
    <!-- /page header -->
    <!-- Content area -->
    <div class="content">
      <%= yield %>
    </div>
   <%= render partial: 'admin/layouts/footer' %>
  </div>
  <!-- /main content -->
</div>
<!-- /page content -->
</body>
</html>

app/views/admin/user_activity.html.erb
<% content_for :title, "學生活動紀錄" %>

<% content_for :script do %>
  <script src="/global_assets/js/demo_pages/datatables_extension_buttons_print.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/extensions/select.min.js"></script>
<% end %>

<div class="row">
  <div class="card col-lg">
    <div class="card-header header-elements-inline">
      <h5 class="card-title">學生活動紀錄</h5>
      <div class="header-elements">
        <div class="list-icons">
          <a class="list-icons-item" data-action="collapse"></a>
          <a class="list-icons-item" data-action="reload"></a>
          <a class="list-icons-item" data-action="remove"></a>
        </div>
      </div>
    </div>

    <table class="table datatable-button-print-rows" style="font-size:16px">
      <thead>
        <tr>
          <td>最近登入時間</td>
          <td>姓名</td>
          <td>班級</td>
          <td>編號</td>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |users| %>
        <tr>
          <td><%= users.current_sign_in_at %></td>
          <td><%= users.name %></td>
          <td><%= users.student_class %></td>
          <td><%= users.id %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="text-center mt-2">
  <a class="btn btn-success" href="">匯出</a>
</div>

app/views/admin/user_manage.html.erb
<% content_for :title, "用戶管理" %>

<% content_for :script do %>
  <script src="/global_assets/js/demo_pages/datatables_extension_buttons_print.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
  <script src="/global_assets/js/plugins/tables/datatables/extensions/select.min.js"></script>
<% end %>

<div class="row">
  <div class="card col-lg">
    <div class="card-header header-elements-inline">
      <h5 class="card-title">用戶管理</h5>
      <div class="header-elements">
        <div class="list-icons">
          <a class="list-icons-item" data-action="collapse"></a>
          <a class="list-icons-item" data-action="reload"></a>
          <a class="list-icons-item" data-action="remove"></a>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table id="zero_config" class="table datatable-button-print-rows">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Class</th>
            <th>Email</th>
            <th>role</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="myTable">
        <% @users.each_with_index do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.student_class %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td>
              <a class="btnSelect btn btn-primary"  href="javascript:void(0);" data-toggle="modal" data-target="#edit_user" data-detail="<%= user.to_json %>">編輯</a>
              <%= link_to '刪除', user_path(user), method: :delete, class: "btn btn-danger", data:{ confirm: "確定要刪除這筆資料嗎?"}%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="edit_user" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="padding: 48px 16px;">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= form_for @edit_user, html: {id: "user_edit_form"}  do |f| %>
              <%= f.label :name, "姓名" %><br/>
              <%= f.text_field :name, class: "form-control", placeholder: "Enter username", required: "required" %>
              <br/>
              <%= f.label :student_class, "班級" %><br/>
              <%= f.text_field :student_class, class: "form-control", placeholder: "Enter class", required: "required" %>
              <br/>
              <%= f.label :email, "電子信箱" %><br/>
              <%= f.text_field :email, class: "form-control", readonly: "readonly"%>
              <br/>
              <%= f.label :role, "身分"%><br/>
              <%= f.text_field :role, class: "form-control", placeholder: "預設為guest 學生是student 管理員是admin", required: "required" %>
              <br/>
              <%= f.submit "修改", class: "btn btn-info", data: { confirm: "是否修改此學生的資料?"} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>


    $(function(){
        $(".btnSelect.btn.btn-primary").click(function(){
            var detail = $(this).data("detail");
            var newURL = "/user/" + detail.id;

            $("#user_edit_form").attr("action", newURL);
            $("#user_name").val(detail.name);
            $("#user_student_class").val(detail.student_class);
            $("#user_email").val(detail.email);
            $("#user_role").val(detail.role);
        })
    });
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container text-center">
    <span class="text-muted">COPYRIGHT BY NCUT IM CHUN LIN & TUNG LIN</span>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">NCUT會展英文</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class=" mr-auto">
        </div>

        <ul class="navbar-nav ml-sm-2">

          <li class="nav-item">
            <% if current_user %>
              <%= link_to '檢視所有資料', user_infos_path, class: "nav-link" %>
              <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                  <%= current_user.name %> <span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to '登出', destroy_user_session_path, method: :delete, class: "nav-link"  %>
                </div>
              </li>
            <% else%>
              <%= link_to '登入', user_session_path, class: "nav-link"%>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
</div>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>